name: flutter_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter_screenutil: ^5.9.3
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  table_calendar: ^3.1.2
  intl: ^0.19.0
  dotted_border: ^2.1.0
  fl_chart: ^0.69.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/colored/
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
    - family: AbhayaLibre
      fonts:
        - asset: assets/fonts/AbhayaLibre-Regular.ttf
          weight: 400
        - asset: assets/fonts/AbhayaLibre-Medium.ttf
          weight: 500
        - asset: assets/fonts/AbhayaLibre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AbhayaLibre-Bold.ttf
          weight: 700

